---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
date: "2024-03-27"
---
```{r}
library("FrF2")
```

```{r}
#load the data
data<-read.csv('sta305_project_data.csv')
hours<-data$hours
physical_activity<-as.factor(data$physical_activity)
Alcohol<-as.factor(data$Alcohol)
Meal<-as.factor(data$Meal)
```

```{r}
#Fit the model
sleep<-lm(hours~physical_activity*Alcohol*Meal, data=data)
summary(sleep)
aov(sleep)
```

```{r}
#Assumption checking
library(car)
qqPlot(sleep$residuals, ylab='residuals', main='Normal Q-Q plot')
plot(sleep$fitted.values, sleep$residuals, xlab='fitted value', ylab='residuals', main='Residual Plot')
abline(h=0)
```

```{r}
#Calculate the effect of each factor and interaction term
data.frame(effect=2*sleep$coefficients)
```

```{r}
#Calculate the confidence interval for factors and interaction terms. 
#confidence interval
2*confint.lm(sleep)
```

```{r}
#Generate half normal plot
DanielPlot(sleep, half= TRUE,autolab = T)
```

```{r}
#Generate the Cube Plot
cubePlot(sleep,'physical_activity', 'Alcohol', 'Meal', main='cube plot for sleep hours')
```

```{r}
#Calculate the variance of effect

#first method
s1=((4-5)^2)/2
s2=((8-5)^2)/2
s3=((8-7)^2)/2
s4=((6-5)^2)/2
s5=((11-9)^2)/2
s6=((8-11)^2)/2
s7=((8-9)^2)/2
s8=((11-10)^2)/2
#pooled variance of hours
s=(s1+s2+s3+s4+s5+s6+s7+s8)/8
var_effect = s/4
print(var_effect)

#Second method
var_effect_2 <- (0.3248*2)**2
print(var_effect_2)
```
